# Generated by Django 2.0.1 on 2018-04-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="brutaldon")),
                ("api_base_id", models.URLField(default="mastodon.social")),
                ("client_id", models.TextField(blank=True, null=True)),
                ("client_secret", models.TextField(blank=True, null=True)),
            ],
        )
    ]
