# Generated by Django 2.0.4 on 2018-04-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brutaldon", "0003_auto_20180424_1255")]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.EmailField(max_length=254),
        )
    ]
