# Generated by Django 2.1 on 2018-08-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brutaldon", "0011_auto_20180825_1017")]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.EmailField(max_length=254, unique=True),
        )
    ]
