# Generated by Django 2.1 on 2018-08-26 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("brutaldon", "0012_auto_20180826_1853")]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="theme",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="brutaldon.Theme",
            ),
        )
    ]
