# Generated by Django 2.1.1 on 2018-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brutaldon", "0013_auto_20180826_1935")]

    operations = [
        migrations.AddField(
            model_name="account", name="note_seen", field=models.IntegerField(null=True)
        )
    ]
