# Generated by Django 2.1.1 on 2018-10-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brutaldon", "0014_account_note_seen")]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="click_to_load",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="preference",
            name="no_javascript",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="preference",
            name="notifications",
            field=models.BooleanField(default=True),
        ),
    ]
