# Generated by Django 2.1.2 on 2018-10-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brutaldon", "0016_auto_20181009_1805")]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="poll_frequency",
            field=models.IntegerField(
                default=300,
                help_text="Number of seconds to wait between checking notifications. Default: 300",
            ),
        )
    ]
